<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProvidersTekus.DAL\ProvidersTekus.DAL.csproj" />
    <ProjectReference Include="..\ProvidersTekus.DTO\ProvidersTekus.DTO.csproj" />
    <ProjectReference Include="..\ProvidersTekus.MODELS\ProvidersTekus.MODELS.csproj" />
    <ProjectReference Include="..\ProvidersTekus.UTILITY\ProvidersTekus.UTILITY.csproj" />
  </ItemGroup>

</Project>
