<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProvidersTekus.DAL\ProvidersTekus.DAL.csproj" />
    <ProjectReference Include="..\ProvidersTekus.DLL\ProvidersTekus.DLL.csproj" />
    <ProjectReference Include="..\ProvidersTekus.UTILITY\ProvidersTekus.UTILITY.csproj" />
  </ItemGroup>

</Project>
